odin_projects/webDev101/RailsBlogger/config/routes.rb
Rails.application.routes.draw do
	root to: 'articles#index'
  resources :articles

  resources :articles do
  	resources :comments
	end
	
	resources :tags

end

odin_projects/webDev101/RailsBlogger/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :attachments

	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ['image/jpg', 'image/jpeg', 'image/png']

	def tag_list
  	self.tags.collect do |tag|
  		tag.name
  	end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(',').map { |tag| tag.strip.downcase }.uniq

		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  	self.tags = new_or_found_tags	
  end

end

odin_projects/webDev101/RailsBlogger/app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :article

	has_attached_file :image
	# styles: { medium: "500x500>", thumb: "100x100>" } -- This doesn't work
	# using paperclip 3.5.4
	# instead I changed it to inline HTML styles

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

odin_projects/webDev101/RailsBlogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

odin_projects/webDev101/RailsBlogger/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

odin_projects/webDev101/RailsBlogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

odin_projects/webDev101/RailsBlogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

odin_projects/webDev101/RailsBlogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
include ArticlesHelper

	def index
		@articles = Article.all
		@tags = Tag.all
	end

	def show
		@article = Article.find(params[:id])

		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
  	@article = Article.new(article_params)
  	@article.save

  	flash.notice = "The article '#{@article.title}' has been created!"

  	redirect_to article_path(@article)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
  	@article.update(article_params)

  	flash.notice = "The article '#{@article.title}' has been updated!"

  	redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		flash.notice = "The article '#{@article.title}' has been deleted!"

		redirect_to articles_path
	end

end

odin_projects/webDev101/RailsBlogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save

		flash.notice = "Your comment was created successfully!"
  	redirect_to article_path(@comment.article_id)
	end

	def comment_params
  	params.require(:comment).permit(:author_name, :body)
	end
end

odin_projects/webDev101/RailsBlogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def show
  	@tag = Tag.find(params[:id])
  	@tag.articles
	end

	def index
		@tags = Tag.all
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		flash.notice = "'#{@tag.name.capitalize}' was successfully deleted!"
		redirect_to tags_path
	end

end

odin_projects/webDev101/RailsBlogger/app/helpers/application_helper.rb
module ApplicationHelper
end

odin_projects/webDev101/RailsBlogger/app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
  
end

odin_projects/webDev101/RailsBlogger/app/helpers/comments_helper.rb
module CommentsHelper
end

odin_projects/webDev101/RailsBlogger/app/helpers/tags_helper.rb
module TagsHelper
end

odin_projects/webDev101/RailsBlogger/app/views/articles/_comment.html.erb
<div>
	<h4>Comment by <%= comment.author_name %></h4>
	<p class="comment"><%= comment.body %></p>
	<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

odin_projects/webDev101/RailsBlogger/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true} ) do |f| %>
	<ul>
		<% @article.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>

	<p>
		<%= f.label :title %> 
		<br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %>
		<br />
		<%= f.text_area :body %>
	</p>

	<p>
  	<%= f.label :tag_list %>
  	<br />
  	<%= f.text_field :tag_list %>
	</p>

<p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url, style: "height: 100px; width: 100px" %><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br />
  <%= f.file_field :image %>
</p>

	<p>
		<%= f.submit %>
	</p>
	
<% end %>

odin_projects/webDev101/RailsBlogger/app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

odin_projects/webDev101/RailsBlogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title' %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

<br />
<br />

<br />
<br />

<h1>All Tags</h1>

<ul id="articles">
	<% @tags.each do |tag| %>
		<br /><li><%= link_to tag.name.capitalize, tag_path(tag), class: 'article_title' %></li>
	<% end %>
</ul>

odin_projects/webDev101/RailsBlogger/app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

odin_projects/webDev101/RailsBlogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<br />

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<br /> <hr />


<p>
	<% if @article.image.exists? %>
		<%= image_tag @article.image.url, style: "height: 400px; width: 400px" %>
	<% end %> 
</p>
<br/>

<p><%= @article.body %></p>
<br /> <br />

<%= link_to "Edit Article", edit_article_path(@article), style: "display: inline" %>

<%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}, style: "display: inline" %>
<br /> <hr /> <br /> 

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<br />

<%= render partial: 'comments/form' %>

<%= link_to "Back to Articles List", articles_path %>
<!-- The class is 'new_article' because I want it in the top right corner, and the 'new_article' css class will put it there. -->
<%= link_to "Back to Articles List", articles_path, class: "new_article" %>

odin_projects/webDev101/RailsBlogger/app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your name" %>
    <br/>
    <%= f.text_field :author_name %>
  </p>

  <p>
    <%= f.label :body, "Your comment" %>
    <br/>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

odin_projects/webDev101/RailsBlogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash.notice %></p>

<%= yield %>

</body>
</html>

odin_projects/webDev101/RailsBlogger/app/views/tags/index.html.erb
<h1>A List of All Tags</h1>

<p>
	<% @tags.each do |tag| %>
		<ul>
			<br /><li><%= link_to tag.name.capitalize, tag_path(tag) %></li>

			<%= link_to "Delete Tag", tag_path(tag), method: :delete, data: {confirm: "Are you sure you want to delete this tag?"} %>
		</ul>
	<% end %>
</p>

<!-- The class is 'new_article' because I want it in the top right corner, and the 'new_article' css class will put it there. -->
<%= link_to "Back to Articles", articles_path, class: "new_article" %>

odin_projects/webDev101/RailsBlogger/app/views/tags/show.html.erb
<h1>Articles Tagged with "<%= @tag.name.capitalize %>"</h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<!-- The class is 'new_article' because I want it in the top right corner, and the 'new_article' css class will put it there. -->
<%= link_to "Back to All Tags", tags_path, class: "new_article" %>